get http://localhost:5000/status


### register
post http://localhost:5000/api/v1/user/register
Content-Type: application/json

{
    "email": "conbocuoi2111@gmail.com",
    "password": "sonha12345",
    "name":"sonha1"
}

###login

post http://localhost:5000/api/v1/user/login
Content-Type: application/json

{   
    "email": "conbocuoi2111@gmail.com",
    "password": "sonha12345"
}